### ISSUE TITLE
comparison with bluebird

### ISSUE THREAD

**Issue by abenhamdine** [rpgeeganage/async-ray#17]
Hi,

Could you explain how your library compare with bluebird collection methods http://bluebirdjs.com/docs/api-reference.html ?

**Comment by rpgeeganage** [comment]
Hi @abenhamdine, 
Thank you very much for opening the first issue in the package.

I'm not sure I can compare the features of BlueBird.
The purpose of the Async-ray package is to work as a utility package, such as Lodash, or underscore.

**Comment by abenhamdine** [comment]
> I'm not sure I can compare the features of BlueBird.

Because Bluebird provides also utilities functions to use async/await with arrays.

Exemple with map : 

with your library :   

```js
const inputArray = [1, 2, 3, 4];

// Call Map method
const mappedArray = await AsyncRay(inputArray).aMap(
  async (i, index, collection) => {
    // Dummy async function
    return await dummy(i);
  }
);
```

with Bluebird (see http://bluebirdjs.com/docs/api/promise.map.html) : 

```js
import { map } from 'bluebird'

const inputArray = [1, 2, 3, 4];

await map(
	inputArray,
	(i, index, length) => return dummy(i)
)
```
Looks pretty similar, it's why I wonder why you created your library and what are the differences.

**Comment by rpgeeganage** [comment]
Hi @ abenhamdine
Thanks for the clarification.
But I hesitate to compare my library with BlueBird.
I would like to use native Promise in my development, hence I rarely use BlueBird or Q.
I'm bit reluctant to use a library like BlueBird or Q only to get features like in my library.
Hence, I developed my own, without using any 3rd party libraries (even BlueBird doesn't use any).
So other developers like me which not required full-feature library like BlueBird can use my library.
